"""Alignment is numerically pinned: a wrong (transposed or non-inverted) matrix still
produces a plausible image, so nothing here judges the crop by eye."""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from app.config import Settings
from app.core.types import ARCFACE_TEMPLATE, CROP_SIZE
from app.pipeline.align import (
    align_crop,
    apply_transform,
    invert_transform,
    similarity_transform,
)


def rotation_scale_translation(angle_deg: float, scale: float, tx: float, ty: float) -> np.ndarray:
    angle = math.radians(angle_deg)
    rotation = np.array(
        [[math.cos(angle), -math.sin(angle)], [math.sin(angle), math.cos(angle)]],
        dtype=np.float64,
    )
    matrix = np.empty((2, 3), dtype=np.float64)
    matrix[:, :2] = scale * rotation
    matrix[:, 2] = (tx, ty)
    return matrix


def ramp_image(height: int, width: int) -> np.ndarray:
    """R = x, G = y, B = 128. Bicubic resampling is exact on a linear ramp, so any pixel
    mismatch is a transform bug rather than interpolation noise."""
    image = np.full((height, width, 3), 128, dtype=np.uint8)
    image[:, :, 0] = np.arange(width, dtype=np.uint8)[None, :]
    image[:, :, 1] = np.arange(height, dtype=np.uint8)[:, None]
    return image


def test_transform_lands_landmarks_on_template() -> None:
    # Landmarks generated by a known similarity from the template: the fit must invert it.
    known = rotation_scale_translation(17.0, 2.3, 140.0, 65.0)
    landmarks = apply_transform(known, ARCFACE_TEMPLATE)

    fitted = similarity_transform(landmarks, ARCFACE_TEMPLATE.astype(np.float64))
    mapped = apply_transform(fitted, landmarks)

    residual = np.linalg.norm(mapped - ARCFACE_TEMPLATE, axis=1)
    assert residual.max() < 1e-3


def test_transform_is_least_squares_under_noise() -> None:
    known = rotation_scale_translation(-8.0, 1.7, 40.0, 25.0)
    rng = np.random.default_rng(7)
    landmarks = apply_transform(known, ARCFACE_TEMPLATE) + rng.normal(0.0, 0.8, (5, 2))

    fitted = similarity_transform(landmarks, ARCFACE_TEMPLATE.astype(np.float64))
    mapped = apply_transform(fitted, landmarks)

    # Perturbed points cannot land exactly, but a similarity fit keeps them within ~1px and
    # the residuals must be centred (a biased fit means the translation term is wrong).
    residual = np.linalg.norm(mapped - ARCFACE_TEMPLATE, axis=1)
    assert residual.max() < 1.5
    assert np.allclose((mapped - ARCFACE_TEMPLATE).mean(axis=0), 0.0, atol=1e-6)


def test_transform_never_mirrors() -> None:
    """A reflected point set must be fitted by a proper rotation, not a mirror."""
    mirrored = ARCFACE_TEMPLATE.astype(np.float64).copy()
    mirrored[:, 0] = 200.0 - mirrored[:, 0]

    fitted = similarity_transform(mirrored, ARCFACE_TEMPLATE.astype(np.float64))

    assert np.linalg.det(fitted[:, :2]) > 0.0


def test_invert_transform_round_trips() -> None:
    matrix = rotation_scale_translation(33.0, 0.7, -12.0, 88.0)
    points = np.array([[0.0, 0.0], [10.0, 4.0], [-3.0, 7.5]])

    back = apply_transform(invert_transform(matrix), apply_transform(matrix, points))

    assert np.allclose(back, points, atol=1e-9)


def test_align_crop_recovers_known_downscale() -> None:
    """The classic bug: Pillow's AFFINE wants the inverse map. With landmarks placed by a
    pure scale-2 + translation, the aligned crop must be exactly the corresponding strided
    slice of the source, i.e. crop[y, x] == image[2y + ty, 2x + tx]."""
    scale, tx, ty = 2.0, 30.0, 20.0
    known = rotation_scale_translation(0.0, scale, tx, ty)
    landmarks = apply_transform(known, ARCFACE_TEMPLATE)
    image = ramp_image(300, 300)

    crop = align_crop(image, landmarks)

    assert crop.shape == (CROP_SIZE, CROP_SIZE, 3)
    assert crop.dtype == np.uint8
    xs = (np.arange(CROP_SIZE) * scale + tx).astype(int)
    ys = (np.arange(CROP_SIZE) * scale + ty).astype(int)
    expected = image[np.ix_(ys, xs)]
    assert np.abs(crop.astype(int) - expected.astype(int)).max() <= 1


def test_align_crop_undoes_rotation() -> None:
    """A source rotated by a known angle must come back upright: a marker pixel painted at
    the transformed position of a template point lands on that template point."""
    known = rotation_scale_translation(25.0, 1.6, 120.0, 90.0)
    landmarks = apply_transform(known, ARCFACE_TEMPLATE)
    image = np.zeros((400, 400, 3), dtype=np.uint8)
    probe = np.array([[56.0, 56.0]])
    px, py = apply_transform(known, probe)[0]
    rounded_y = round(py)
    rounded_x = round(px)
    image[rounded_y - 1 : rounded_y + 2, rounded_x - 1 : rounded_x + 2] = 255

    crop = align_crop(image, landmarks)

    bright = np.argwhere(crop[:, :, 0] > 100)
    assert bright.size > 0
    centre = bright.mean(axis=0)  # (row, col)
    assert abs(centre[0] - 56.0) < 1.5
    assert abs(centre[1] - 56.0) < 1.5


def test_align_crop_fills_out_of_frame_with_black() -> None:
    """A face at the border keeps the template geometry and pads, rather than shifting."""
    known = rotation_scale_translation(0.0, 1.0, -40.0, 0.0)
    landmarks = apply_transform(known, ARCFACE_TEMPLATE)
    image = np.full((112, 112, 3), 200, dtype=np.uint8)

    crop = align_crop(image, landmarks)

    assert crop[:, :5].max() == 0
    assert crop[:, 80:].min() == 200


def test_align_crop_rejects_bad_shapes() -> None:
    with pytest.raises(ValueError, match="RGB image"):
        align_crop(np.zeros((10, 10), dtype=np.uint8), ARCFACE_TEMPLATE)
    with pytest.raises(ValueError, match="landmarks"):
        align_crop(np.zeros((10, 10, 3), dtype=np.uint8), np.zeros((4, 2), dtype=np.float32))


def test_similarity_transform_rejects_degenerate_points() -> None:
    with pytest.raises(ValueError, match="degenerate"):
        similarity_transform(np.zeros((5, 2)), ARCFACE_TEMPLATE.astype(np.float64))


def _fixture_face() -> Path | None:
    root = Settings().fixtures_dir
    if not root.is_dir():
        return None
    for jpeg in sorted(root.glob("*/*.jpg")):
        return jpeg
    return None


def test_align_crop_on_real_image_is_bounded() -> None:
    """Image-dependent sanity check: a real photo aligned with plausible landmarks yields a
    non-degenerate crop. Skips cleanly where FIXTURES_DIR has no faces (CI)."""
    face = _fixture_face()
    if face is None:
        pytest.skip("no fixtures/<identity>/*.jpg available")
    image = np.asarray(Image.open(face).convert("RGB"), dtype=np.uint8)
    # LFW-funneled faces are roughly centred at a known scale; this is a coarse guess, good
    # enough to assert the warp produced real image content rather than padding.
    guess = apply_transform(rotation_scale_translation(0.0, 1.6, 35.0, 30.0), ARCFACE_TEMPLATE)

    crop = align_crop(image, guess)

    assert crop.shape == (CROP_SIZE, CROP_SIZE, 3)
    assert crop.std() > 5.0
